"""Initial migration

Revision ID: 142d40907367
Revises: 
Create Date: 2024-06-07 18:04:51.068597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142d40907367'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alerts',
    sa.Column('coin_id', sa.Uuid(), nullable=False),
    sa.Column('threshold_price', sa.Float(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.Enum('INCREASE', 'DECREASE', name='alerttype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coins_prices',
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timedate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coin_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins_prices')
    op.drop_table('alerts')
    op.drop_table('coins')
    # ### end Alembic commands ###
