"""Delete enum

Revision ID: 38887eae4aa6
Revises: 142d40907367
Create Date: 2024-06-09 16:50:32.296256

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38887eae4aa6'
down_revision: Union[str, None] = '142d40907367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'alert_type',
               existing_type=postgresql.ENUM('INCREASE', 'DECREASE', name='alerttype'),
               type_=sa.String(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.String(length=3),
               type_=postgresql.ENUM('INCREASE', 'DECREASE', name='alerttype'),
               existing_nullable=False)
    # ### end Alembic commands ###
