"""update uniq

Revision ID: 5cdf266fd461
Revises: 5771c18f5aec
Create Date: 2024-06-11 04:58:36.042241

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5cdf266fd461'
down_revision: Union[str, None] = '5771c18f5aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coin_alert_type', 'alerts', type_='unique')
    op.create_unique_constraint('coin_alert_type', 'alerts', ['email', 'coin_id', 'alert_type', 'threshold_price'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coin_alert_type', 'alerts', type_='unique')
    op.create_unique_constraint('coin_alert_type', 'alerts', ['coin_id', 'alert_type', 'threshold_price'])
    # ### end Alembic commands ###
